version: '3.1'

services:
  postgres:
    image: postgres:14.4-alpine3.16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
    restart: always
  pgadmin4:
    image: dpage/pgadmin4:6.11
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 9000
    ports:
      - 9000:9000
    depends_on:
      - postgres
